name: grisette-examples
version: 0.1.0.0
synopsis: Examples for Grisette
description: Example symbolic DSLs for Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-examples
copyright: "2021-2022 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette >= 0.2 && < 0.3

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

executables:
  arith-synth:
    source-dirs: arith-synth
    main: Main.hs
