name: datalab
version: 0.1.0.0
github: "lsrcz/grisette-examples"
license: BSD-3-Clause
author: "Sirui Lu"
maintainer: "siruilu@cs.washington.edu"
copyright: "2023 Sirui Lu"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lsrcz/grisette-examples/tree/main/datalab>

dependencies:
  - base >= 4.7 && < 5
  - grisette >= 0.4.1 && < 0.5
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  datalab:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - datalab
