name: arith-synth
version: 0.1.0.0
synopsis: A synthesizer for arithmetic expressions.
description: A synthesizer for arithmetic expressions.
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-examples
copyright: "2021-2023 Sirui Lu"

dependencies:
  - base >= 4.14 && < 5
  - grisette >= 0.3 && < 0.4

ghc-options: -Wall -ferror-spans

executables:
  arith-synth:
    source-dirs: app
    main: Main.hs
